# Generated by Django 4.1.3 on 2022-12-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_word_pronounce_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='scene_text_path',
        ),
        migrations.AddField(
            model_name='character',
            name='scene_text_from',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='名场面来源'),
        ),
        migrations.AlterField(
            model_name='character',
            name='memory',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='联想记忆'),
        ),
    ]
