# Generated by Django 4.1.3 on 2022-12-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='pronounce_url',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='单词发音地址'),
        ),
    ]
