# Generated by Django 4.1.3 on 2022-12-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_character_scene_text_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mini_time',
        ),
        migrations.AddField(
            model_name='user',
            name='min_time',
            field=models.IntegerField(default=10000000, verbose_name='五十音游戏最短时间'),
        ),
    ]
