# Generated by Django 4.1.3 on 2022-12-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_mini_time_user_min_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='learned_chapter',
            field=models.ManyToManyField(related_name='users', to='api.chapter', verbose_name='学习过的章节'),
        ),
        migrations.CreateModel(
            name='AnimeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='动漫名称')),
                ('animes', models.ManyToManyField(blank=True, related_name='categories', to='api.anime', verbose_name='相关动漫')),
            ],
        ),
    ]
