# Generated by Django 4.1.3 on 2022-12-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_learned_chapter_animecategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animecategory',
            options={'verbose_name_plural': '动漫分类'},
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('normal', '正常账户'), ('blocked', '封号账户'), ('leaved', '注销账户')], default='normal', max_length=12, verbose_name='账户状态'),
        ),
    ]
